name: ${project.name}
version: ${project.version}
main: ${mainClass}
depend: [KotlinLibrary,BountyHunterCore]
softdepend:
  - PlaceholderAPI
authors: [KunSs]
description: SpigotKotlinSDK plugina
api-version: 1.13
commands:
  ua: